version: '3.0'
services:
  db:
    image: "postgres"
    ports:
      - "5555:5432"
    environment:
      POSTGRES_DB: booking
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
  app:
    build: .
    ports:
      - "8900:8080"
    depends_on:
      - db
  java:

volumes:
  db: