server:
  ssl:
    key-password: bookingappssl
    key-store-password: bookingappssl
    key-store: classpath:keystore.jks
  servlet:
    context-path: /api
  error:
    include-message: always
booking:
  page:
    number: 0
    size: 10
    sortBy: name
  security:
    tokenPrefix: Bearer
    secretKey: nzZtxusf7MZ8wW3oNRV70nqXi98B6g5L
    validity: 3600000
    rememberMe: 14
  scheduler:
    confirmReservations:
      cron: "0 0/1 * * * *"
      partitionSize: 10000
logging:
  file:
    name: logs/application.log
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/booking
    username: booking
    password: booking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  flyway:
    baseline-on-migrate: true