CREATE TABLE SPECIALIZATIONS(
                      SPC_ID INT PRIMARY KEY NOT NULL,
                      SPC_CODE VARCHAR(10) NOT NULL,
                      SPC_NAME VARCHAR(50) NOT NULL,
                      CONSTRAINT SPC_CODE_UNIQUE UNIQUE (SPC_CODE),
                      CONSTRAINT SPC_NAME_UNIQUE UNIQUE (SPC_NAME)
);

COMMENT ON COLUMN SPECIALIZATIONS.SPC_ID IS 'Specialization ID (primary key)';
COMMENT ON COLUMN SPECIALIZATIONS.SPC_CODE IS 'Specialization business code (unique)';
COMMENT ON COLUMN SPECIALIZATIONS.SPC_NAME IS 'Specialization name (unique)';

CREATE SEQUENCE SPC_SEQ
    START WITH 1
    INCREMENT BY 50
    MINVALUE 1
    MAXVALUE 100000000
    CYCLE;