CREATE TABLE WORKING_HOURS(
                          WRH_ID INT PRIMARY KEY NOT NULL,
                          WRH_MONDAY_F TIME(6),
                          WRH_MONDAY_T TIME(6),
                          WRH_TUESDAY_F TIME(6),
                          WRH_TUESDAY_T TIME(6),
                          WRH_WEDNESDAY_F TIME(6),
                          WRH_WEDNESDAY_T TIME(6),
                          WRH_THURSDAY_F TIME(6),
                          WRH_THURSDAY_T TIME(6),
                          WRH_FRIDAY_F TIME(6),
                          WRH_FRIDAY_T TIME(6),
                          WRH_SATURDAY_F TIME(6),
                          WRH_SATURDAY_T TIME(6),
                          WRH_SUNDAY_F TIME(6),
                          WRH_SUNDAY_T TIME(6)
);

COMMENT ON COLUMN WORKING_HOURS.WRH_ID IS 'Working hours ID (primary key)';
COMMENT ON COLUMN WORKING_HOURS.WRH_MONDAY_F IS 'Monday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_MONDAY_T IS 'Monday to';
COMMENT ON COLUMN WORKING_HOURS.WRH_TUESDAY_F IS 'Tuesday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_TUESDAY_T IS 'Tuesday to';
COMMENT ON COLUMN WORKING_HOURS.WRH_WEDNESDAY_F IS 'Wednesday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_WEDNESDAY_T IS 'Wednesday to';
COMMENT ON COLUMN WORKING_HOURS.WRH_THURSDAY_F IS 'Thursday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_THURSDAY_T IS 'Thursday to';
COMMENT ON COLUMN WORKING_HOURS.WRH_FRIDAY_F IS 'Friday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_FRIDAY_T IS 'Friday to';
COMMENT ON COLUMN WORKING_HOURS.WRH_SATURDAY_F IS 'Saturday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_SATURDAY_T IS 'Saturday to';
COMMENT ON COLUMN WORKING_HOURS.WRH_SUNDAY_F IS 'Sunday from';
COMMENT ON COLUMN WORKING_HOURS.WRH_SUNDAY_T IS 'Sunday to';

CREATE SEQUENCE WRH_SEQ
    START WITH 1
    INCREMENT BY 50
    MINVALUE 1
    MAXVALUE 100000000
    CYCLE;