CREATE TABLE ROLES(
                      ROL_ID INT PRIMARY KEY NOT NULL,
                      ROL_TYPE VARCHAR(30) NOT NULL,
                      CONSTRAINT ROL_TYPE_UNIQUE UNIQUE (ROL_TYPE)
);

COMMENT ON COLUMN ROLES.ROL_ID IS 'Role ID (primary key)';
COMMENT ON COLUMN ROLES.ROL_TYPE IS 'Role type (unique)';

CREATE SEQUENCE ROL_SEQ
    START WITH 1
    INCREMENT BY 50
    MINVALUE 1
    MAXVALUE 100000000
    CYCLE;

INSERT INTO ROLES VALUES(nextval('ROL_SEQ'), 'USER');
INSERT INTO ROLES VALUES(nextval('ROL_SEQ'), 'COMPANY_USER');
INSERT INTO ROLES VALUES(nextval('ROL_SEQ'), 'ADMIN');

COMMIT;