CREATE TABLE RESERVATIONS(
                      RES_ID INT PRIMARY KEY NOT NULL,
                      RES_DATE TIMESTAMP NOT NULL,
                      RES_LOC_ID INT REFERENCES LOCATIONS (LOC_ID) NOT NULL,
                      RES_USR_ID INT REFERENCES USERS (USR_ID),
                      RES_VSR_ID INT REFERENCES VIRTUAL_USERS (VSR_ID),
                      RES_SRV_ID INT REFERENCES SERVICES (SRV_ID) NOT NULL,
                      RES_EMP_ID INT REFERENCES EMPLOYEES (EMP_ID) NOT NULL,
                      RES_STATUS VARCHAR(1),
                      RES_CREATION_DATE TIMESTAMP DEFAULT now() NOT NULL,
                      RES_MODIFICATION_DATE TIMESTAMP,
                      RES_CANCELLATION_DATE TIMESTAMP,
                      RES_CANCELLATION_REASON VARCHAR(255)
);

COMMENT ON COLUMN RESERVATIONS.RES_ID IS 'Reservation ID (primary key)';
COMMENT ON COLUMN RESERVATIONS.RES_DATE IS 'Reservation date';
COMMENT ON COLUMN RESERVATIONS.RES_LOC_ID IS 'Reservation location (foreign key)';
COMMENT ON COLUMN RESERVATIONS.RES_USR_ID IS 'Reservation user (foreign key)';
COMMENT ON COLUMN RESERVATIONS.RES_USR_ID IS 'Reservation virtual user (foreign key)';
COMMENT ON COLUMN RESERVATIONS.RES_SRV_ID IS 'Reservation service (foreign key)';
COMMENT ON COLUMN RESERVATIONS.RES_EMP_ID IS 'Reservation employee (foreign key)';
COMMENT ON COLUMN RESERVATIONS.RES_STATUS IS 'Reservation status';
COMMENT ON COLUMN RESERVATIONS.RES_CREATION_DATE IS 'Reservation creation date';
COMMENT ON COLUMN RESERVATIONS.RES_MODIFICATION_DATE IS 'Reservation modification date';
COMMENT ON COLUMN RESERVATIONS.RES_CANCELLATION_DATE IS 'Reservation cancellation date';
COMMENT ON COLUMN RESERVATIONS.RES_CANCELLATION_REASON IS 'Reservation cancellation reason';

CREATE SEQUENCE RES_SEQ
    START WITH 1
    INCREMENT BY 50
    MINVALUE 1
    MAXVALUE 100000000
    CYCLE;