CREATE TABLE EMPLOYEES_SERVICES(
                            EMPLOYEES_EMP_ID INT REFERENCES EMPLOYEES (EMP_ID) NOT NULL,
                            SERVICES_SRV_ID INT REFERENCES SERVICES (SRV_ID) NOT NULL
)