CREATE TABLE COMPANIES_SPECIALIZATIONS(
                                   COMPANIES_CMP_ID INT REFERENCES COMPANIES (CMP_ID) NOT NULL,
                                   SPECIALIZATIONS_SPC_ID INT REFERENCES SPECIALIZATIONS (SPC_ID) NOT NULL
)